# Site
repository: Enzovo/Enzovo.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Qiyun Chen (Enzo)
title: Student
gender: male
email: enzo.chen0915@gmail.com
website: Enzovo.github.io
phone: +1-(848)-37-1226

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  Enzovo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: qiyun-chen-90506b285
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Qiyun Chen and you will be very welcome to call me Enzo. 
  I was a student at Rutgers University NB and majored in Computer Science.
  And I will start my Master of Science & Engineering in Computer Science at UC San Diego in fall 2024.
  
  I'm also self-motivated and solutions-oriented professional with a strong track
  record in <mark>software development</mark>, specializing in <mark>socket communication</mark> and
  <mark>Flask</mark> API design. Possessing robust problem-solving abilities, particularly
  in <mark>algorithm development</mark> and <mark>data cleaning</mark>. Proficient in multiple
  programming languages, with a focus on <mark>Python</mark>, <mark>C</mark>, and <mark>Java</mark>. Adept at
  collaborating with cross-cultural, global teams to deliver high-quality results.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Some interesting projects
        link: github.com/Enzovo
        # link_text: Project Website
        additional_links:
          - title:  some projects
            icon: fab fa-github
            url: github.com/Enzovo
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          There are some interesting projects in different repositories! Happy to share with you!
        description: | # this will include new lines to allow paragraphs
          There is one project about an online Tic-tac-toe game, which is implemented in C language. This server can allow multiple games to be played together, which use <mark>select</mark> to handle blocking I/O.   

          Also, a classic chess game with an Android Application is here. If you are a chessman, don't hesitate to clone it and start one game with your friend or in-game AI(not a really smart one).  

          And, a fast trajectory re-planning project is also here. It implements <mark>A*</mark> Algorithm with Python that is applied to the agent maze event.  

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: SVIEF(San Jose, CA USA)
        link: www.svief.org
        # link_text: boringcompany.com
        sub_title: IT Developer
        caption: May 2024 - August 2024
        quote: >
          The Silicon Valley High-Tech Innovation and Entrepreneurship Summit (abbreviated as SVIEF) 
          was founded in 2011 in Silicon Valley, California, USA. It is a large-scale platform dedicated 
          to promoting high-tech industry technology, investment, and talent exchange between China 
          and the United States. Every year, SVIEF hosts a major annual event in the heart of global 
          innovation and entrepreneurship—Silicon Valley—featuring the High-Tech Innovation and 
          Entrepreneurship Summit and the High-Tech Technology Fair. After seven years of development, 
          it has become a high-end international entrepreneurial and investment conference that connects 
          China and the United States, while also extending its influence to North America and the 
          Asia-Pacific region. The event attracts tens of thousands of elites from the business, 
          political, and technology sectors each year. Over the past decade, it has become the most 
          prestigious and largest professional platform between China and the United States, 
          providing industry professionals with high-level, information-rich, and personalized 
          business information exchanges, resource matching, talent recruitment, project 
          matchmaking, and venture capital services.  
        description: | # this will include new lines to allow paragraphs
          Designed and implemented custom web architectures to support
          various project requirements.  

          Led efforts in data collection and cleaning, ensuring high-quality,
          usable datasets.  

          Conducted in-depth data analysis, turning raw data into actionable
          insights.  

          Developed clean, efficient, and well-tested code across multiple
          projects.  

          Identified, verified, and resolved bugs and issues to enhance
          software performance
          

        title: Shenzhen InSigma - Artificial Intelligence Research Institute (China)
        link: szis.com.cn
        # link_text: boringcompany.com
        sub_title: Python Developer (Intern)
        caption: August 2023 - March 2024
        quote: >
          Shenzhen InSigma Software Co., Ltd. is a cutting-edge information service provider based in South China with a global reach. Established in 2012 and headquartered in Shenzhen, China, the company is dedicated to delivering reliable and comprehensive new-generation information services.  
        description: | # this will include new lines to allow paragraphs
          Using python lib <mark>PyMuPDF</mark> to make an API with <mark>Flask</mark> that can grab all the data from a pdf according to format. And provide this to the Lead Algorithm Developer for AI model training purposes.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Rutgers University New Brunswick
        caption: 2021 - 2024
        sub_title: BS Computer Science
        quote: >
          Rutgers, The State University of New Jersey, stands among America's highest-ranked, most diverse public research universities. The oldest, largest, and top-ranked public university in the New York/New Jersey metropolitan area, you'll find us at our main locations in three New Jersey cities, and our footprint can be seen around the region. We're an academic, health, and research powerhouse and a university of opportunity.
        description: | # this will include new lines to allow paragraphs
          My time at Rutgers was truly exceptional. As a multicultural institution, I rarely encountered any cultural barriers, and Rutgers' inclusive environment facilitated my swift integration into the community as a Chinese student. In the Computer Science major, I had the opportunity to delve into a variety of programming languages. For instance, I gained proficiency in C language through the <mark>System Programming</mark> course and honed my skills in designing interactive interfaces and functions in the <mark>Software Methodology</mark> course. Additionally, I delved into the realm of data structures and algorithms, exploring various algorithmic concepts in the <mark>Introduction to Algorithms</mark> course, which significantly heightened my interest in this field.  

          Furthermore, my coursework included acquiring knowledge in data management through the study of <mark>Data Management</mark> where I gained proficiency in tools such as <mark>NumPy</mark>, <mark>Pandas</mark>, and <mark>Matplotlib</mark>. These skills equipped me with the ability to effectively process and analyze data.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Computer Science some of my other interests and hobbies are:
      - Soccer (Chinese Soccer Team Goal Keeper at Rutgers)
      - Basketball (Lebron is my goat all the time)
      - Swimming
      - Gaming(Csgo never die! LoL is also an option)

      Look at this cool image when we were against with Upenn Chinese Soccer Team   
      ![Soccer](images/soccer.jpg "Soccer!")

# Footer
footer_show_references: true
references_title: Thanks to sproogen for the amazing website template

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
