# Site
repository: Enzovo/Enzovo.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Qiyun Chen (Enzo)
title: Student
gender: male
email: enzo.chen0915@gmail.com
website: Enzovo.github.io
phone: +1-(848)-37-1226

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  Enzovo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: qiyun-chen-90506b285
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Qiyun Chen and you will be very welcome to call me Enzo. I'm a senior student at Rutgers University NB and major in Computer Science. Experienced in socket communication and multithreading and offering skills in algorithm problem solving and programming. Fluent in Python, C and Java programming.  

  I am most skilled in <mark>Python Development</mark> and interested in <mark>Machine Learning</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Some interesting projects
        link: github.com/Enzovo
        # link_text: Project Website
        additional_links:
          - title:  some projects
            icon: fab fa-github
            url: github.com/Enzovo
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          There are some interesting projects in different repositories! Happy to share with you!
        description: | # this will include new lines to allow paragraphs
          There is one project about an online Tic-tac-toe game, which is implemented in C language. This server can allow multiple games to be played together, which use <mark>select</mark> to handle blocking I/O.   
          Also, a classic chess game with an Android Application is here. If you are a chessman, don't hesitate to clone it and start one game with your friend or in-game AI(not a really smart one).  
          And, a fast trajectory re-planning project is also here. It implements <mark>A*</mark> Algorithm with Python that is applied to the agent maze event.  

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Shenzhen InSigma - Artificial Intelligence Research Institute (China)
        link: szis.com.cn
        # link_text: boringcompany.com
        sub_title: Python Developer (Intern)
        caption: August 2023 - Present
        quote: >
          Using python lib <mark>PyMuPDF</mark> to make an API with <mark>Flask</mark> that can grab all the data from a pdf according to format. And provide this to the Lead Algorithm Developer for AI model training purposes.
        description: | # this will include new lines to allow paragraphs
          Shenzhen NetXinXinsi Software Co., Ltd. is a cutting-edge information service provider based in South China with a global reach. Established in 2012 and headquartered in Shenzhen, China, the company is dedicated to delivering reliable and comprehensive new-generation information services.  
          Currently, we have established extensive and profound strategic partnerships with industry leaders such as Ping An Group, GF Securities, TCL Group, Taiping Jinke, SF Express Group, Hong Kong Jockey Club, DJI, Harman, Philips, NetEase, and other major players. Our commitment extends beyond the domestic market as we actively address the offshore service needs of international clients. Leveraging local cost advantages, skills, and other resources, we employ a global delivery model that seamlessly integrates with offshore development centers throughout China. This approach allows us to fuse advanced project management, architecture, and business development capabilities with local delivery expertise, ensuring the provision of stable, efficient, and comprehensive new-generation information services.  
          As a prominent software service company in China, we steadfastly adhere to the service philosophy of "low cost, low risk, high quality." Our focus revolves around accelerating customers' profit growth, continually enhancing efficiency, and advancing product capabilities through the application of new-generation information technology. Quality and market responsiveness are anticipated to serve as the core driving forces supporting our customers' business expansion.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
references_title: Thanks to sproogen for the amazing website template

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
